# If you see me, please update my `rev` field using the provided links
# Click the repo and update to latest tags.
# If things break on update, raise an issue
repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort imports tabular_data_experiments
        files: tabular_data_experiments

      - id: isort
        name: isort imports tests
        files: tests

  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
      - id: black
        name: black formatter tabular_data_experiments
        files: tabular_data_experiments

      - id: black
        name: black formatter tests
        files: tests

      - id: black
        name: black formatter examples
        files: examples

  # - repo: https://github.com/pycqa/pydocstyle
  #   rev: 6.1.1
  #   hooks:
  #     - id: pydocstyle
  #       files: tabular_data_experiments
  #       additional_dependencies: ["toml"] # Needed to parse pyproject.toml

  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v0.930
  #   hooks:
  #     - id: mypy
  #       name: mypy tabular_data_experiments
  #       files: tabular_data_experiments

  # - repo: https://github.com/pycqa/flake8
  #   rev: 4.0.1
  #   hooks:
  #     - id: flake8
  #       name: flake8 tabular_data_experiments
  #       files: tabular_data_experiments

  #     - id: flake8
  #       name: flake8 tests
  #       files: tests
